--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Kingbobs/Relics
build-by-default: true
branches:
- master
projects: []

Open the CI at https://poggit.pmmp.io/ci/Kingbobs/Relics
Come Check It Out
